version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-autenticacao
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_autenticacao
    volumes:
      - pg_data_autenticacao:/var/lib/postgresql/data
    networks:
      - pagamentos-network

volumes:
  pg_data_autenticacao:

networks:
  pagamentos-network:
    driver: bridge