services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-autenticacao
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_autenticacao
    volumes:
      - pg_data_autenticacao:/var/lib/postgresql/data
    networks:
      - pagamentos-network

  postgres-transacoes:
    image: postgres:15-alpine
    container_name: postgres-transacoes
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_transacoes
    volumes:
      - pg_data_transacoes:/var/lib/postgresql/data
    networks:
      - pagamentos-network

  db-notificacoes:
    image: postgres:15-alpine
    container_name: postgres-notificacoes
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=db_notificacoes
    volumes:
      - pg_data_notificacoes:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: pagamentos-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - pagamentos-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: pagamentos-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - pagamentos-network
      
volumes:
  pg_data_autenticacao:
  pg_data_transacoes:
  pg_data_notificacoes:

networks:
  pagamentos-network:
    driver: bridge